[project]
name = "proyecto-clean-csv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.0",
    "ruff>=0.15.1",
]

[tool.ruff]
line-length = 100
select = ["E", "F", "W", "C"]